---

- hosts: localhost
  tasks:
    - name: Prepare folder for credentials
      file:
        path: "{{ inventory_dir }}/.credentials/{{ item }}/users/{{ hostvars[item]['ansible_user'] }}/"
        state: directory
        mode: 0755
      with_items: "{{ groups['servers'] }}"

    - name: Download private keys for servers
      hashivault_read:
        mount_point: "secrets"
        secret: "nodes/{{ item }}/users/{{ hostvars[item]['ansible_user'] }}"
        key: 'private_key'
        version: 2
      with_items: "{{ groups['servers'] }}"
      loop_control:
        label: "{{ item }}"
      register: 'private_keys'

    - name: Write private key to file
      copy:
        content: "{{ item.value }}"
        dest: "{{ inventory_dir }}/.credentials/{{ item.item }}/users/{{ hostvars[item.item]['ansible_user'] }}/id_rsa"
        mode: 0600
      with_items: "{{ private_keys.results }}"
      loop_control:
        label: "{{ item.item }}"


- hosts: servers
  become: true

  vars:
    consul_host: "consul.service.consul"
    consul_port: "8500"

    docker_registry: ghcr.io
    docker_username: "{{ lookup('hashivault', 'services/ghcr', 'user', mount_point='/secrets', version=2) }}"
    docker_password: "{{ lookup('hashivault', 'services/ghcr', 'password', mount_point='/secrets', version=2) }}"

    private_network: "{{ ansible_eth1['ipv4'] }}"

    services_dir: /opt/services

    heimdall_sentry_dsn: "{{ lookup('hashivault', 'services/heimdall', 'sentry_dsn', mount_point='/secrets', version=2) }}"

    heimdall_image: ghcr.io/clayman-micro/heimdall
    heimdall_version: "{{ lookup('env','HEIMDALL_VERSION')|default('latest') }}"

    heimdall_domain: "`passport.{{ domain }}`"

    heimdall_passport:
      host: passport.clayman.pro
      backend: passport.service.consul:5000

    heimdall_services:
      - name: wallet
        host: wallet.clayman.pro
        backend: wallet.service.consul:5000

    heimdall_replicas: 1

  roles:
    - role: heimdall
