
---

- hosts: servers
  become: true

  vars:
    domain: clayman.pro

    consul_host: "consul.service.consul"
    consul_port: "8500"

    private_network: "{{ ansible_eth1['ipv4'] }}"

    image: ghcr.io/clayman-micro/heimdall

    version: "{{ lookup('env','VERSION')|default('latest') }}"

    replicas: "{{ lookup('env', 'REPLICAS')|default(1) }}"

  tasks:
    - name: Pull image
      docker_image:
        name: "{{ image }}:{{ version }}"
        source: pull

    - name: Update service
      docker_swarm_service:

        name: heimdall

        image: "{{ image }}:{{ version }}"
        command: python3 -m shortner server run
        args:
          - "--tags={{ env }}"
        dns:
          - "{{ private_network.address }}"
        env:
          CONSUL_HOST: "{{ consul_host }}"
          CONSUL_PORT: "{{ consul_port }}"
        logging:
          driver: syslog
          options:
            syslog-address: unixgram:///dev/log

            tag: heimdall

        networks:
          - backend
        replicas: "{{ replicas }}"
        limits:
          cpus: '0.50'
          memory: 64M

